package com.example.monstersappmodule8.login;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;
import androidx.room.Update;

@Dao
public interface UserDAO {

    @Insert(onConflict = OnConflictStrategy.ABORT)
    Long insert(User user); //returns the autogenerated ID

    @Update
    void update(User user);

    @Delete
    void delete(User user);

//  For examples accessing data from the DB
//  https://developer.android.com/training/data-storage/room/accessing-data

    @Query("SELECT * FROM USER WHERE ID= :id")
    User findById(Integer id);

    @Query("SELECT * FROM USER WHERE UPPER(EMAIL) = UPPER(:email)")
    User findByEmail(String email);

}
